runtime: nodejs20
env: standard
instance_class: F1

# Automatic scaling chỉ dùng min_instances và max_instances
automatic_scaling:
  min_instances: 1   # Số instance tối thiểu luôn chạy
  max_instances: 10  # Số instance tối đa, tránh cảnh báo từ 3/2025

# Định tuyến tất cả request tới Node.js app
handlers:
  - url: /.*
    script: auto
