runtime: nodejs18
env: standard
instance_class: F1

# Cấu hình automatic scaling
automatic_scaling:
  min_instances: 1       # số instance tối thiểu luôn chạy, có thể để 0 nếu muốn tiết kiệm
  max_instances: 10      # số instance tối đa
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

handlers:
  - url: /.*
    script: auto

# Tùy chọn logging (khuyến nghị)
beta_settings:
  cloud_sql_instances: ""
